SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS app_users (
  username VARCHAR(191) PRIMARY KEY,
  login_name VARCHAR(191) NULL,
  full_name TEXT NULL,
  position TEXT NULL,
  department TEXT NULL,
  role VARCHAR(80) NULL,
  email VARCHAR(191) NULL,
  special_position TEXT NULL,
  token TEXT NULL,
  legacy_password TEXT NULL,
  extra LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_app_users_login_name (login_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS draft_requests (
  draft_id VARCHAR(191) PRIMARY KEY,
  username VARCHAR(191) NULL,
  doc_date DATE NULL,
  requester_name TEXT NULL,
  requester_position TEXT NULL,
  location TEXT NULL,
  province TEXT NULL,
  purpose TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  attendees LONGTEXT NULL,
  expense_option TEXT NULL,
  expense_items LONGTEXT NULL,
  total_expense DECIMAL(14,2) NULL,
  vehicle_option TEXT NULL,
  license_plate TEXT NULL,
  department TEXT NULL,
  head_name TEXT NULL,
  status TEXT NULL,
  timestamp_source DATETIME NULL,
  extra LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_draft_requests_username (username),
  INDEX idx_draft_requests_doc_date (doc_date),
  INDEX idx_draft_requests_timestamp_source (timestamp_source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS requests (
  request_id VARCHAR(191) PRIMARY KEY,
  created_by VARCHAR(191) NULL,
  ref_number TEXT NULL,
  doc_date DATE NULL,
  requester_name TEXT NULL,
  requester_position TEXT NULL,
  location TEXT NULL,
  purpose TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  duration TEXT NULL,
  expense_option TEXT NULL,
  expense_items LONGTEXT NULL,
  total_expense DECIMAL(14,2) NULL,
  vehicle_option TEXT NULL,
  license_plate TEXT NULL,
  department TEXT NULL,
  head_name TEXT NULL,
  pdf_url TEXT NULL,
  created_at_source DATETIME NULL,
  status TEXT NULL,
  command_pdf_url TEXT NULL,
  command_status TEXT NULL,
  command_pdf_url_solo TEXT NULL,
  command_pdf_url_group_small TEXT NULL,
  command_pdf_url_group_large TEXT NULL,
  dispatch_book_pdf_url TEXT NULL,
  item_1 TEXT NULL,
  qty_1 DECIMAL(12,2) NULL,
  item_2 TEXT NULL,
  qty_2 DECIMAL(12,2) NULL,
  item_3 TEXT NULL,
  qty_3 DECIMAL(12,2) NULL,
  item_4 TEXT NULL,
  qty_4 DECIMAL(12,2) NULL,
  item_5 TEXT NULL,
  qty_5 DECIMAL(12,2) NULL,
  item_6 TEXT NULL,
  qty_6 DECIMAL(12,2) NULL,
  item_7 TEXT NULL,
  qty_7 DECIMAL(12,2) NULL,
  command_doc_url_solo TEXT NULL,
  command_doc_url_group_large TEXT NULL,
  doc_url TEXT NULL,
  command_doc_url_group_small TEXT NULL,
  province TEXT NULL,
  stay_at TEXT NULL,
  dispatch_vehicle_type TEXT NULL,
  dispatch_vehicle_id TEXT NULL,
  completed_memo_url TEXT NULL,
  completed_command_url TEXT NULL,
  memo_status TEXT NULL,
  dispatch_book_url TEXT NULL,
  admin_memo_url TEXT NULL,
  doc_status VARCHAR(120) NULL,
  was_rejected TINYINT(1) NULL,
  rejection_reason TEXT NULL,
  command_template_type TEXT NULL,
  extra LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_requests_created_by (created_by),
  INDEX idx_requests_status (status(120)),
  INDEX idx_requests_doc_status (doc_status),
  INDEX idx_requests_doc_date (doc_date),
  INDEX idx_requests_start_date (start_date),
  INDEX idx_requests_created_at_source (created_at_source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  request_id VARCHAR(191) NOT NULL,
  source_row_key VARCHAR(191) UNIQUE,
  full_name TEXT NOT NULL,
  position TEXT NULL,
  source_date_text TEXT NULL,
  attended_at DATETIME NULL,
  extra LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_attendees_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memos (
  memo_id VARCHAR(191) PRIMARY KEY,
  submitted_by VARCHAR(191) NULL,
  ref_number VARCHAR(191) NULL,
  status TEXT NULL,
  created_at_source DATETIME NULL,
  file_id TEXT NULL,
  file_url TEXT NULL,
  completed_memo_url TEXT NULL,
  completed_command_url TEXT NULL,
  dispatch_book_url TEXT NULL,
  admin_memo_url TEXT NULL,
  memo_pdf_url TEXT NULL,
  current_pdf_url TEXT NULL,
  dispatch_status TEXT NULL,
  completed_dispatch_book_url TEXT NULL,
  doc_status VARCHAR(120) NULL,
  rejected_at DATETIME NULL,
  finalized_at DATETIME NULL,
  last_updated_source DATETIME NULL,
  extra LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_memos_ref_number (ref_number),
  INDEX idx_memos_status (status(120)),
  INDEX idx_memos_created_at_source (created_at_source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trash_requests (
  trash_id VARCHAR(191) PRIMARY KEY,
  source_row_key VARCHAR(191) UNIQUE,
  request_id VARCHAR(191) NULL,
  created_by TEXT NULL,
  ref_number TEXT NULL,
  doc_date DATE NULL,
  requester_name TEXT NULL,
  requester_position TEXT NULL,
  location TEXT NULL,
  purpose TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  duration TEXT NULL,
  expense_option TEXT NULL,
  expense_items LONGTEXT NULL,
  total_expense DECIMAL(14,2) NULL,
  vehicle_option TEXT NULL,
  license_plate TEXT NULL,
  department TEXT NULL,
  head_name TEXT NULL,
  pdf_url TEXT NULL,
  created_at_source DATETIME NULL,
  status TEXT NULL,
  command_pdf_url TEXT NULL,
  command_status TEXT NULL,
  command_pdf_url_solo TEXT NULL,
  command_pdf_url_group_small TEXT NULL,
  command_pdf_url_group_large TEXT NULL,
  dispatch_book_pdf_url TEXT NULL,
  command_doc_url_solo TEXT NULL,
  command_doc_url_group_large TEXT NULL,
  doc_url TEXT NULL,
  command_doc_url_group_small TEXT NULL,
  province TEXT NULL,
  stay_at TEXT NULL,
  dispatch_vehicle_type TEXT NULL,
  dispatch_vehicle_id TEXT NULL,
  completed_memo_url TEXT NULL,
  completed_command_url TEXT NULL,
  deleted_at DATETIME NULL,
  deleted_by TEXT NULL,
  extra LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_trash_requests_request_id (request_id),
  INDEX idx_trash_requests_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS request_counters (
  year_be INT PRIMARY KEY,
  current_count INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS approval_links (
  token VARCHAR(191) PRIMARY KEY,
  request_id VARCHAR(191) NULL,
  safe_id TEXT NULL,
  role TEXT NULL,
  used TINYINT(1) NOT NULL DEFAULT 0,
  created_by VARCHAR(191) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used_at DATETIME NULL,
  expires_at DATETIME NULL,
  extra LONGTEXT NULL,
  INDEX idx_approval_links_request_id (request_id),
  INDEX idx_approval_links_used (used)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_settings (
  `key` VARCHAR(191) PRIMARY KEY,
  value LONGTEXT NULL,
  updated_by VARCHAR(191) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS system_config (
  `key` VARCHAR(191) PRIMARY KEY,
  value LONGTEXT NULL,
  updated_by VARCHAR(191) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
